# Generated by Django 5.0.4 on 2024-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sumanmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Documents/')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('upload_time', models.TimeField(auto_now_add=True)),
                ('textdata', models.TextField(blank=True)),
            ],
        ),
    ]
